### ISSUE TITLE
Allow Creation of Clusters in a user Controlled Subnet

### ISSUE THREAD

**Issue by MadVikingGod** [awslabs/aws-eks-cluster-controller#52]
Currently it is not possible to create an EKS Cluster outside of the 192.168.0.0/16 subnet.  

*Expected Resulsts* 
When defining a cluster a network and subnets can be specified. For example
```yaml
network:
    vpcCider: "192.168.0.0/16"
    subnet1: "192.168.64.0/18"
    subnet2: "192.168.128.0/18"
    subnet3: "192.168.192.0/18"
```
And the cluster will be created with the correct subnets.

**Comment by anand99** [comment]
Is it ok to use following spec for network information:
```
    network:
      vpcCidr: "172.16.0.0/16"
      subnetOneCidr: "172.16.0.0/24"
      subnetTwoCidr: "172.16.1.0/24"
      subnetThreeCidr: "172.16.2.0/24"
```

Due to https://github.com/kubernetes-sigs/controller-tools/issues/139 the fields with Digit in yaml spec not ending in CRD.
